version: '3.8'
services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # - ./app:/app
      - ./:/code
    working_dir: /code/
    command: uvicorn src.main:app --host 0.0.0.0 --reload